In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys, os
sys.path.append(os.path.abspath(".."))
print(sys.path)

['/home/codespace/.python/current/lib/python312.zip', '/home/codespace/.python/current/lib/python3.12', '/home/codespace/.python/current/lib/python3.12/lib-dynload', '', '/workspaces/tastetester/.venv/lib/python3.12/site-packages', '/workspaces/tastetester']

In [1]:
import json

import pandas as pd
from etl.common.vectorstore import ListeningVectorStore

store = ListeningVectorStore()
tracks = store.execute("SELECT * FROM track_details").fetchall()
df_tracks = pd.DataFrame.from_records(tracks, columns=tracks[0].keys(), index="spotify_track_uri")
df_tracks['genres'] = df_tracks['genres'].apply(lambda x: json.loads(x) or [])
df_tracks['top_genre'] = df_tracks['genres'].apply(lambda x: x[0] if len(x) > 0 else None)
display(df_tracks.head())

df_tracks['total_plays'].hist(by=df_tracks["top_genre"], figsize=(20, 20))

ModuleNotFoundError: No module named 'etl'

In [25]:
from app.recommender import Recommender
import logging

logging.getLogger().setLevel(logging.DEBUG)

track = "09eSdS5RTgyodJt3krr5AC"
recommendations = Recommender().analyze(track)
print(recommendations)

DEBUG:root:Loading vector store
DEBUG:root:Fetching track details for 09eSdS5RTgyodJt3krr5AC
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.reccobeats.com:443
DEBUG:urllib3.connectionpool:https://api.reccobeats.com:443 "GET /v1/track?ids=09eSdS5RTgyodJt3krr5AC HTTP/1.1" 200 None
DEBUG:root:Got details {'id': '27736c03-57ac-40ba-b6ba-b2971f2cee25', 'trackTitle': 'Answer', 'artists': [{'id': 'a5223065-e579-44e9-8fb5-e11508acfa49', 'name': 'Phantogram', 'href': 'https://open.spotify.com/artist/1l9d7B8W0IHy3LqWsxP2SH'}], 'durationMs': 231600, 'isrc': 'USUM71605177', 'ean': None, 'upc': None, 'href': 'https://open.spotify.com/track/09eSdS5RTgyodJt3krr5AC', 'availableCountries': 'AR,AU,AT,BE,BO,BR,BG,CA,CL,CO,CR,CY,CZ,DK,DO,DE,EC,EE,SV,FI,FR,GR,GT,HN,HK,HU,IS,IE,IT,LV,LT,LU,MY,MT,MX,NL,NZ,NI,NO,PA,PY,PE,PH,PL,PT,SG,SK,ES,SE,CH,TW,TR,UY,US,GB,AD,LI,MC,ID,JP,TH,VN,RO,IL,ZA,SA,AE,BH,QA,OM,KW,EG,MA,DZ,TN,LB,JO,PS,IN,BY,KZ,MD,UA,AL,BA,HR,ME,MK,RS,SI,KR,BD,PK,LK,GH,KE,NG,TZ,UG,AG,AM,BS,BB,BZ,BT,BW,BF,CV,CW,DM,FJ,GM,GE,GD,GW,GY,HT,JM,KI,LS,LR,MW,MV,ML,MH,FM,NA,NR,NE,PW,PG,WS,SM,ST,SN,SC,SL,SB,KN,LC,VC,SR,TL,TO,TT,TV,VU,AZ,BN,BI,KH,CM,TD,KM,GQ,SZ,GA,GN,KG,LA,MO,MR,MN,NP,RW,TG,UZ,ZW,BJ,MG,MU,MZ,AO,CI,DJ,ZM,CD,CG,IQ,LY,TJ,VE,ET,XK', 'popularity': 44}
DEBUG:root:Fetching audio features for 09eSdS5RTgyodJt3krr5AC
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.reccobeats.com:443
DEBUG:urllib3.connectionpool:https://api.reccobeats.com:443 "GET /v1/audio-features?ids=09eSdS5RTgyodJt3krr5AC HTTP/1.1" 200 None
DEBUG:root:Got features {'content': [{'id': '27736c03-57ac-40ba-b6ba-b2971f2cee25', 'href': 'https://open.spotify.com/track/09eSdS5RTgyodJt3krr5AC', 'isrc': 'USUM71605177', 'acousticness': 0.129, 'danceability': 0.362, 'energy': 0.371, 'instrumentalness': 0.0441, 'key': 11, 'liveness': 0.121, 'loudness': -8.383, 'mode': 0, 'speechiness': 0.0324, 'tempo': 148.376, 'valence': 0.107}]}
DEBUG:root:Fetching genres for Phantogram
DEBUG:musicbrainzngs:set user-agent to trydionel-ds-project/0.0.1 python-musicbrainzngs/0.7.1 ( jeff@trydionel.com )
DEBUG:musicbrainzngs:GET request for https://musicbrainz.org/ws/2/artist/?limit=1&query=artist%3A%28phantogram%29
DEBUG:musicbrainzngs:requesting with UA trydionel-ds-project/0.0.1 python-musicbrainzngs/0.7.1 ( jeff@trydionel.com )
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:area>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:begin-area>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:alias>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:alias>, uncaught attribute type-id
DEBUG:root:Got genres ['indie pop', 'indietronica', 'glitch pop']
DEBUG:root:Prepared [-0.446506   -1.4953592   0.9125677  -0.02319499 -0.6500625  -1.3648355
 -0.44190514 -0.47758478 -0.14605328  0.          0.          0.
  0.          0.          0.          0.          0.          1.
  0.          0.          0.          1.          0.          1.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.        ] for similarity search
DEBUG:root:Found most similar listening history [{'entity_key': 'spotify:track:09eSdS5RTgyodJt3krr5AC', 'distance': 3.3119485465249454e-07}, {'entity_key': 'spotify:track:3XWL3vnY0fIT5416rWBe7C', 'distance': 2.0349159240722656}, {'entity_key': 'spotify:track:7oFLIwPHL5gLtde7ukFvsX', 'distance': 2.1770808696746826}, {'entity_key': 'spotify:track:2hYvrq8ImKNGaHpHLDXR9e', 'distance': 2.5506346225738525}, {'entity_key': 'spotify:track:1fYdtAhgGLKmOZE46mCGm0', 'distance': 2.5599076747894287}]
DEBUG:root:Fetching details for similar listening history
DEBUG:root:Phantogram - Answer (14 listens, 0.00 distance)
DEBUG:root:Phantogram - Never Going Home (1 listens, 2.03 distance)
DEBUG:root:Phantogram - Destroyer (6 listens, 2.18 distance)
DEBUG:root:Collapse Under The Empire - A Riot of Emotion (1 listens, 2.55 distance)
DEBUG:root:Phantogram - All A Mystery (1 listens, 2.56 distance)
[I 2026-06-08 23:27:31,850] A new study created in memory with name: no-name-58dc4ec3-bfdf-406a-a513-ccc44764a378
[W 2026-06-08 23:27:31,878] Trial 0 failed with parameters: {'n_estimators': 437, 'max_depth': 12, 'learning_rate': 0.07587945476302646, 'tree_method': 'exact'} because of the following error: ValueError('DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:track_name: object, artist_name: object, album_name: object, genres: object, top_genre: object').
Traceback (most recent call last):
  File "/workspaces/tastetester/.venv/lib/python3.12/site-packages/xgboost/data.py", line 408, in pandas_feature_info
    new_feature_types.append(_pandas_dtype_mapper[dtype.name])
                             ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'object'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/tastetester/.venv/lib/python3.12/site-packages/optuna/study/_optimize.py", line 205, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "<string>", line 11, in objective
  File "/workspaces/tastetester/.venv/lib/python3.12/site-packages/xgboost/core.py", line 751, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/workspaces/tastetester/.venv/lib/python3.12/site-packages/xgboost/sklearn.py", line 1343, in fit
    train_dmatrix, evals = _wrap_evaluation_matrices(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/tastetester/.venv/lib/python3.12/site-packages/xgboost/sklearn.py", line 700, in _wrap_evaluation_matrices
    train_dmatrix = create_dmatrix(
                    ^^^^^^^^^^^^^^^
  File "/workspaces/tastetester/.venv/lib/python3.12/site-packages/xgboost/sklearn.py", line 1262, in _create_dmatrix
    return DMatrix(**kwargs, nthread=self.n_jobs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/tastetester/.venv/lib/python3.12/site-packages/xgboost/core.py", line 751, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/workspaces/tastetester/.venv/lib/python3.12/site-packages/xgboost/core.py", line 976, in __init__
    handle, feature_names, feature_types = dispatch_data_backend(
                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/tastetester/.venv/lib/python3.12/site-packages/xgboost/data.py", line 1429, in dispatch_data_backend
    return _from_pandas_df(
           ^^^^^^^^^^^^^^^^
  File "/workspaces/tastetester/.venv/lib/python3.12/site-packages/xgboost/data.py", line 706, in _from_pandas_df
    df, feature_names, feature_types = _transform_pandas_df(
                                       ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/tastetester/.venv/lib/python3.12/site-packages/xgboost/data.py", line 668, in _transform_pandas_df
    feature_names, feature_types = pandas_feature_info(
                                   ^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/tastetester/.venv/lib/python3.12/site-packages/xgboost/data.py", line 410, in pandas_feature_info
    _invalid_dataframe_dtype(data)
  File "/workspaces/tastetester/.venv/lib/python3.12/site-packages/xgboost/data.py", line 373, in _invalid_dataframe_dtype
    raise ValueError(msg)
ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:track_name: object, artist_name: object, album_name: object, genres: object, top_genre: object
[W 2026-06-08 23:27:31,889] Trial 0 failed with value None.

ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:track_name: object, artist_name: object, album_name: object, genres: object, top_genre: object

In [13]:
distances = store.execute("SELECT entity_key, vec_distance_cosine(vector, (SELECT vector FROM track_content_vectors LIMIT 1)) AS distance FROM track_content_vectors").fetchall()
df_distances = pd.DataFrame.from_records(distances, columns=distances[0].keys())

df_distances['distance'].describe()

count    5.340000e+02
mean     9.612464e-01
std      3.231277e-01
min     -2.220446e-16
25%      7.432737e-01
50%      9.771225e-01
75%      1.202131e+00
max      1.646639e+00
Name: distance, dtype: float64

In [14]:
from sklearn.metrics.pairwise import pairwise_distances

vectors = store.execute("SELECT entity_key, vec_to_json(vector) AS vector FROM track_content_vectors").fetchall()
keys = store.execute("SELECT feature_columns FROM vector_registry").fetchone()

def parse_row(row):
  entity_key = row['entity_key']
  vector = json.loads(row['vector'])

  return [entity_key] + vector

columns = ['entity_key'] + json.loads(keys['feature_columns'])

df_vectors = pd.DataFrame.from_records(map(parse_row, vectors), columns=columns, index='entity_key')
df_vectors = df_vectors.dropna()
display(df_vectors.head())

df_pairwise_distances = pairwise_distances(df_vectors, metric='cosine')
df_pairwise_distances

,danceability,energy,tempo,acousticness,valence,instrumentalness,liveness,speechiness,loudness,genre:alternative rock,...,genre:progressive metal,genre:progressive rock,genre:psychedelic pop,genre:psychedelic rock,genre:rock,genre:space rock,genre:stoner metal,genre:stoner rock,genre:synthwave,genre:trip hop
entity_key,,,,,,,,,,,,,,,,,,,,,
spotify:track:00RYw42tKwXecTaVay3BKl,1.016082,1.168719,-0.824202,-0.470081,-0.440962,-1.482137,-0.021799,-0.221650,1.565109,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
spotify:track:01PW4iTCvh9cUHPF0eV7H3,-0.869723,1.141809,1.169956,-0.534343,1.127291,-1.482305,-0.641739,0.158056,1.227448,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
spotify:track:01iiEi9h8CQGUN2K1xBbTj,-0.153988,0.392817,-1.002272,-0.185808,-0.231862,-1.480911,-0.544093,-0.286683,0.518211,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
spotify:track:01s8hwUgHNbSL4mJtaEtNK,-1.336506,-0.347204,0.386224,-0.500894,-0.768870,0.880444,-0.419197,-0.337031,-0.125165,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
spotify:track:02FPjj5HyCRQMbE3egggh6,-1.212031,1.177689,0.307122,-0.526260,-0.988900,0.357728,-0.396488,-0.007672,1.259887,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

array([[0.        , 0.71346369, 0.50674901, ..., 0.83865728, 1.21317833,
        0.8930585 ],
       [0.71346369, 0.        , 0.74338603, ..., 1.17802029, 0.81260105,
        0.82114956],
       [0.50674901, 0.74338603, 0.        , ..., 1.02856062, 1.21269797,
        1.1935418 ],
       ...,
       [0.83865728, 1.17802029, 1.02856062, ..., 0.        , 0.62725264,
        0.78168201],
       [1.21317833, 0.81260105, 1.21269797, ..., 0.62725264, 0.        ,
        0.67590427],
       [0.8930585 , 0.82114956, 1.1935418 , ..., 0.78168201, 0.67590427,
        0.        ]], shape=(534, 534))

In [19]:
df_all = df_tracks.join(df_vectors.filter(like='genre:'), rsuffix="_")
display(df_all.head())

print(df_tracks.columns)
print(df_all.columns)

,track_name,artist_name,album_name,total_plays,total_playtime_ms,years_listened,most_recent_year,peak_year,danceability,energy,...,genre:progressive metal,genre:progressive rock,genre:psychedelic pop,genre:psychedelic rock,genre:rock,genre:space rock,genre:stoner metal,genre:stoner rock,genre:synthwave,genre:trip hop
spotify_track_uri,,,,,,,,,,,,,,,,,,,,,
spotify:track:00RYw42tKwXecTaVay3BKl,Howling At The Moon,Phantogram,Voices,1,238186,1,2017,2017.0,0.597,0.965,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
spotify:track:0129SdVdz3RBtafIMgN1pu,My opinion,deadmau5,stuff i used to do,1,248453,1,2017,2017.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
spotify:track:01AwwfC3sYLbtmECslpj2O,Try again,deadmau5,stuff i used to do,4,689764,1,2017,2017.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
spotify:track:01PW4iTCvh9cUHPF0eV7H3,Time Consumer,Coheed and Cambria,The Second Stage Turbine Blade (Re-Issue),2,683386,1,2018,2018.0,0.294,0.959,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
spotify:track:01iiEi9h8CQGUN2K1xBbTj,List Of People (To Try And Forget About),Tame Impala,Currents B-Sides & Remixes,1,279986,1,2019,2019.0,0.409,0.792,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

Index(['track_name', 'artist_name', 'album_name', 'total_plays',
       'total_playtime_ms', 'years_listened', 'most_recent_year', 'peak_year',
       'danceability', 'energy', 'tempo', 'acousticness', 'valence',
       'instrumentalness', 'liveness', 'speechiness', 'loudness', 'genres',
       'total_tracks', 'release_date_year', 'top_genre'],
      dtype='object')
Index(['track_name', 'artist_name', 'album_name', 'total_plays',
       'total_playtime_ms', 'years_listened', 'most_recent_year', 'peak_year',
       'danceability', 'energy', 'tempo', 'acousticness', 'valence',
       'instrumentalness', 'liveness', 'speechiness', 'loudness', 'genres',
       'total_tracks', 'release_date_year', 'top_genre',
       'genre:alternative rock', 'genre:art punk', 'genre:audiobook',
       'genre:author', 'genre:darksynth', 'genre:electronic', 'genre:folk',
       'genre:french', 'genre:glitch pop', 'genre:hard rock',
       'genre:has german audiobooks', 'genre:house', 'genre:indie pop',
       'genre:indie rock', 'genre:indietronica', 'genre:instrumental',
       'genre:instrumental rock', 'genre:math rock', 'genre:neo-psychedelia',
       'genre:pop', 'genre:pop rock', 'genre:post-metal', 'genre:post-punk',
       'genre:post-rock', 'genre:progressive house', 'genre:progressive metal',
       'genre:progressive rock', 'genre:psychedelic pop',
       'genre:psychedelic rock', 'genre:rock', 'genre:space rock',
       'genre:stoner metal', 'genre:stoner rock', 'genre:synthwave',
       'genre:trip hop'],
      dtype='object')

In [20]:
from scipy import stats
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
import numpy as np

df_train = df_all.dropna()
l_all = len(df_all)
print(f"Total tracks in dataset: {l_all}")

total_plays = df_train['total_plays']

# z_scores = np.abs(stats.zscore(total_plays))
# z_threshold = 5
# df_train = df_train[z_scores < z_threshold]
# print(f"Total outliers removed: {l_all - len(df_train)}")

print(f"Average number of plays for tracks in dataset: {total_plays.mean()}")
print(f"Median number of plays for tracks in dataset: {total_plays.median()}")

X = df_train[df_vectors.columns].copy()
# X = X.drop(columns='genre:pop')
# X = pd.DataFrame(sm.add_constant(X))
display(X.head())

y = df_train['total_plays'].copy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = sm.GLM(y_train, X_train, family=sm.families.Poisson())
results = model.fit(scale='x2')

print(results.summary())

from sklearn.metrics import mean_absolute_error, r2_score
preds = results.predict(X_test)
print('MAE:', mean_absolute_error(y_test.values, preds))
print('corrcoef:', np.corrcoef(y_test.values, preds)[0,1])
print('r^2:', r2_score(y_test.values, preds))

model = sm.GLM(y, X, family=sm.families.Poisson())
results = model.fit(scale='x2')

Total tracks in dataset: 792
Average number of plays for tracks in dataset: 5.252873563218391
Median number of plays for tracks in dataset: 2.0

,danceability,energy,tempo,acousticness,valence,instrumentalness,liveness,speechiness,loudness,genre:alternative rock,...,genre:progressive metal,genre:progressive rock,genre:psychedelic pop,genre:psychedelic rock,genre:rock,genre:space rock,genre:stoner metal,genre:stoner rock,genre:synthwave,genre:trip hop
spotify_track_uri,,,,,,,,,,,,,,,,,,,,,
spotify:track:00RYw42tKwXecTaVay3BKl,0.597,0.965,100.029,0.016600,0.1510,0.000116,0.1950,0.0446,-1.420,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
spotify:track:01PW4iTCvh9cUHPF0eV7H3,0.294,0.959,155.541,0.000437,0.4810,0.000053,0.0858,0.0627,-2.794,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
spotify:track:01iiEi9h8CQGUN2K1xBbTj,0.409,0.792,95.072,0.088100,0.1950,0.000576,0.1030,0.0415,-5.680,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
spotify:track:01s8hwUgHNbSL4mJtaEtNK,0.219,0.627,133.724,0.008850,0.0820,0.886000,0.1250,0.0391,-8.298,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
spotify:track:02FPjj5HyCRQMbE3egggh6,0.239,0.967,131.522,0.002470,0.0357,0.690000,0.1290,0.0548,-2.662,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:            total_plays   No. Observations:                  417
Model:                            GLM   Df Residuals:                      389
Model Family:                 Poisson   Df Model:                           27
Link Function:                    Log   Scale:                          5.6434
Method:                          IRLS   Log-Likelihood:                -259.17
Date:                Mon, 08 Jun 2026   Deviance:                       1716.7
Time:                        23:12:21   Pearson chi2:                 2.20e+03
No. Iterations:                     7   Pseudo R-squ. (CS):             0.3188
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
danceability                    0.1074      0.461      0.233      0.816      -0.797       1.012
energy                         -0.6271      0.452     -1.387      0.166      -1.513       0.259
tempo                           0.0019      0.002      0.928      0.353      -0.002       0.006
acousticness                   -1.0998      0.323     -3.403      0.001      -1.733      -0.466
valence                         0.0874      0.369      0.237      0.813      -0.636       0.811
instrumentalness               -0.0601      0.242     -0.249      0.804      -0.534       0.414
liveness                       -0.4950      0.345     -1.437      0.151      -1.170       0.180
speechiness                     0.9181      1.533      0.599      0.549      -2.086       3.922
loudness                       -0.0432      0.023     -1.910      0.056      -0.087       0.001
genre:alternative rock          0.1873      0.266      0.705      0.481      -0.333       0.708
genre:art punk                  0.2251      0.279      0.806      0.420      -0.322       0.773
genre:audiobook                 0.4099      0.308      1.330      0.184      -0.194       1.014
genre:author                    0.4099      0.308      1.330      0.184      -0.194       1.014
genre:darksynth                 0.4715      0.193      2.439      0.015       0.093       0.850
genre:electronic                0.5250      0.353      1.487      0.137      -0.167       1.217
genre:folk                      0.1184      1.120      0.106      0.916      -2.077       2.314
genre:french                    0.3781      0.680      0.556      0.578      -0.955       1.712
genre:glitch pop                0.4901      0.325      1.509      0.131      -0.147       1.127
genre:hard rock                 0.2559      0.276      0.927      0.354      -0.285       0.797
genre:has german audiobooks     0.4099      0.308      1.330      0.184      -0.194       1.014
genre:house                    -0.2992      0.317     -0.942      0.346      -0.921       0.323
genre:indie pop                 0.4647      0.459      1.013      0.311      -0.434       1.364
genre:indie rock                0.3638      0.311      1.168      0.243      -0.247       0.974
genre:indietronica              0.4901      0.325      1.509      0.131      -0.147       1.127
genre:instrumental              1.2786      0.712      1.795      0.073      -0.117       2.674
genre:instrumental rock         0.7278      0.261      2.788      0.005       0.216       1.239
genre:math rock                 1.3514      0.373      3.626      0.000       0.621       2.082
genre:neo-psychedelia           0.5717      0.166      3.444      0.001       0.246       0.897
genre:pop                       0.3715      0.410      0.906      0.365      -0.432       1.175
genre:pop rock                  0.0189      0.727      0.026      0.979      -1.406       1.444
genre:post-metal                1.3514      0.373      3.626      0.000       0.621       2.082
genre:post-punk                 0.2251      0.279      0.806      0.420      -0.322       0.773
genre:post-rock                -0.2140      0.881     -0.243      0.808      -1.940       1.512
genre:progressive house        -0.2992      0.317     -0.942      0.346      -0.921       0.323
genre:progressive metal         0.0882      0.523      0.169      0.866      -0.937       1.114
genre:progressive rock          0.1873      0.266      0.705      0.481      -0.333       0.708
genre:psychedelic pop           0.5717      0.166      3.444      0.001       0.246       0.897
genre:psychedelic rock          0.7105      0.273      2.604      0.009       0.176       1.245
genre:rock                      0.1180      0.445      0.265      0.791      -0.753       0.989
genre:space rock                0.1387      0.271      0.513      0.608      -0.392       0.669
genre:stoner metal              0.2559      0.276      0.927      0.354      -0.285       0.797
genre:stoner rock               0.2559      0.276      0.927      0.354      -0.285       0.797
genre:synthwave                 0.4715      0.193      2.439      0.015       0.093       0.850
genre:trip hop                  1.1369      0.837      1.358      0.174      -0.504       2.778
===============================================================================================
MAE: 5.11247649579449
corrcoef: 0.44776930848555085
r^2: 0.16292892016082727

In [21]:
import xgboost as xgb
import optuna

def objective(trial):
  pruning_callback = optuna.integration.XGBoostPruningCallback(trial, 'validation_0-poisson-nloglik')
  params = {
    "n_estimators": trial.suggest_int("n_estimators", 100, 1000),
    "max_depth": trial.suggest_int("max_depth", 6, 12),
    "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1),
    "tree_method": trial.suggest_categorical("tree_method", ["exact", "approx", "hist"]),
    "objective": "count:poisson",
    "eval_metric": "poisson-nloglik",
    "seed": 42,
    "callbacks": [pruning_callback],
    "early_stopping_rounds": 50
  }


  model = xgb.XGBRegressor(**params)
  model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=False)
  results = model.evals_result()
  return np.max(results['validation_0']['poisson-nloglik'])


study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective, n_trials=50)

model = xgb.XGBRegressor(**study.best_params)
model.fit(X, y)
print(model.score(X, y))

[I 2026-06-08 23:12:32,819] A new study created in memory with name: no-name-c454811b-bd7e-4d90-bc5e-b45a2dcdedd4

[I 2026-06-08 23:12:35,011] Trial 0 finished with value: 7.794917903627668 and parameters: {'n_estimators': 437, 'max_depth': 12, 'learning_rate': 0.07587945476302646, 'tree_method': 'exact'}. Best is trial 0 with value: 7.794917903627668.
[I 2026-06-08 23:12:35,707] Trial 1 finished with value: 8.001934268361046 and parameters: {'n_estimators': 152, 'max_depth': 12, 'learning_rate': 0.0641003510568888, 'tree_method': 'hist'}. Best is trial 1 with value: 8.001934268361046.
[I 2026-06-08 23:12:35,879] Trial 2 finished with value: 6.819049058641706 and parameters: {'n_estimators': 850, 'max_depth': 7, 'learning_rate': 0.02636424704863906, 'tree_method': 'hist'}. Best is trial 1 with value: 8.001934268361046.
[I 2026-06-08 23:12:36,090] Trial 3 finished with value: 7.505321749051412 and parameters: {'n_estimators': 489, 'max_depth': 8, 'learning_rate': 0.06506676052501416, 'tree_method': 'hist'}. Best is trial 1 with value: 8.001934268361046.
[I 2026-06-08 23:12:36,584] Trial 4 finished with value: 7.307988844599042 and parameters: {'n_estimators': 510, 'max_depth': 11, 'learning_rate': 0.02797064039425238, 'tree_method': 'approx'}. Best is trial 1 with value: 8.001934268361046.
[I 2026-06-08 23:12:36,672] Trial 5 pruned. Trial was pruned at iteration 22.
[I 2026-06-08 23:12:36,687] Trial 6 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:36,863] Trial 7 pruned. Trial was pruned at iteration 22.
[I 2026-06-08 23:12:36,887] Trial 8 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,092] Trial 9 pruned. Trial was pruned at iteration 22.
[I 2026-06-08 23:12:37,268] Trial 10 pruned. Trial was pruned at iteration 29.
[I 2026-06-08 23:12:37,288] Trial 11 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,307] Trial 12 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,327] Trial 13 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,347] Trial 14 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,371] Trial 15 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,390] Trial 16 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,422] Trial 17 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,445] Trial 18 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,477] Trial 19 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,509] Trial 20 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,542] Trial 21 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,570] Trial 22 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,745] Trial 23 pruned. Trial was pruned at iteration 28.
[I 2026-06-08 23:12:37,810] Trial 24 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,829] Trial 25 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,865] Trial 26 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:37,892] Trial 27 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:38,041] Trial 28 pruned. Trial was pruned at iteration 22.
[I 2026-06-08 23:12:38,061] Trial 29 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:38,103] Trial 30 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:38,352] Trial 31 pruned. Trial was pruned at iteration 22.
[I 2026-06-08 23:12:38,593] Trial 32 pruned. Trial was pruned at iteration 22.
[I 2026-06-08 23:12:38,826] Trial 33 pruned. Trial was pruned at iteration 22.
[I 2026-06-08 23:12:39,392] Trial 34 finished with value: 8.041863137199766 and parameters: {'n_estimators': 501, 'max_depth': 12, 'learning_rate': 0.06853316917112351, 'tree_method': 'approx'}. Best is trial 34 with value: 8.041863137199766.
[I 2026-06-08 23:12:39,971] Trial 35 pruned. Trial was pruned at iteration 23.
[I 2026-06-08 23:12:40,605] Trial 36 finished with value: 8.025950340997605 and parameters: {'n_estimators': 579, 'max_depth': 12, 'learning_rate': 0.06866823211442138, 'tree_method': 'approx'}. Best is trial 34 with value: 8.041863137199766.
[I 2026-06-08 23:12:40,632] Trial 37 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:40,657] Trial 38 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:40,689] Trial 39 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:40,724] Trial 40 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:41,320] Trial 41 finished with value: 8.01853437083108 and parameters: {'n_estimators': 388, 'max_depth': 12, 'learning_rate': 0.06643324640938264, 'tree_method': 'approx'}. Best is trial 34 with value: 8.041863137199766.
[I 2026-06-08 23:12:41,346] Trial 42 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:41,788] Trial 43 finished with value: 7.99565247126988 and parameters: {'n_estimators': 410, 'max_depth': 11, 'learning_rate': 0.06052568786559644, 'tree_method': 'approx'}. Best is trial 34 with value: 8.041863137199766.
[I 2026-06-08 23:12:42,185] Trial 44 pruned. Trial was pruned at iteration 52.
[I 2026-06-08 23:12:42,366] Trial 45 pruned. Trial was pruned at iteration 17.
[I 2026-06-08 23:12:42,395] Trial 46 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:42,736] Trial 47 finished with value: 7.928627173105876 and parameters: {'n_estimators': 339, 'max_depth': 10, 'learning_rate': 0.06192442187214297, 'tree_method': 'approx'}. Best is trial 34 with value: 8.041863137199766.
[I 2026-06-08 23:12:42,762] Trial 48 pruned. Trial was pruned at iteration 0.
[I 2026-06-08 23:12:43,009] Trial 49 pruned. Trial was pruned at iteration 17.

0.8917219042778015

In [24]:
vector = recommendations['vector']

input = pd.DataFrame.from_records([vector], columns=store.feature_columns())
# input = input.drop(columns='genre:pop')
# input = pd.DataFrame(sm.add_constant(input))
# input = input.reindex(columns=X.columns, fill_value=0)
display(input)

expected_plays = model.predict(input)
print(f"Expected number of plays for {recommendations['details']['artists'][0]['name']} - {recommendations['details']['trackTitle']}: {expected_plays[0]:.2f}")

,danceability,energy,tempo,acousticness,valence,instrumentalness,liveness,speechiness,loudness,genre:alternative rock,...,genre:progressive metal,genre:progressive rock,genre:psychedelic pop,genre:psychedelic rock,genre:rock,genre:space rock,genre:stoner metal,genre:stoner rock,genre:synthwave,genre:trip hop
0,-0.446506,-1.495359,0.912568,-0.023195,-0.650063,-1.364836,-0.441905,-0.477585,-0.146053,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Expected number of plays for Phantogram - Answer: 8.00

In [11]:
df_tracks.sort_values(by='total_plays').tail(1)

,track_name,artist_name,album_name,total_plays,total_playtime_ms,years_listened,most_recent_year,peak_year,danceability,energy,...,acousticness,valence,instrumentalness,liveness,speechiness,loudness,genres,total_tracks,release_date_year,top_genre
spotify_track_uri,,,,,,,,,,,,,,,,,,,,,
spotify:track:5tVKO8f1v0aTBuOllPxqX0,Hunter Moon,Russian Circles,Blood Year,57,7397454,7,2025,2022.0,0.273,0.0575,...,0.0907,0.0595,0.851,0.0917,0.042,-24.132,"[math rock, post-metal, post-rock]",7.0,2019,math rock